---

- name: Create sessions dev dir
  file: path=/dev/shm/dg-doorstroming/var/sessions/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create cache dev dir
  file: path=/dev/shm/dg-doorstroming/var/cache/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create logs dev dir
  file: path=/dev/shm/dg-doorstroming/var/logs/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Composer install
  command: composer install --no-interaction --prefer-source --no-scripts --working-dir=/vagrant/dg-doorstroming
