---
- name: Create sessions dev dir
  file: path=/dev/shm/jurysysteem_api/var/sessions/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create cache dev dir
  file: path=/dev/shm/jurysysteem_api/var/cache/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create logs dir
  file: path=/dev/shm/jurysysteem_api/var/logs/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Copy the parameters distfile
  command: cp /vagrant/gymnastics-competition-system-api/.env.dist /vagrant/gymnastics-competition-system-api/.env creates=/vagrant/gymnastics-competition-system-api/.env

- name: Composer install
  command: composer install --no-interaction --prefer-source --no-scripts --working-dir=/vagrant/gymnastics-competition-system-api

#- name: Doctrine migrations
#  command: bin/console doctrine:migrations:migrate --no-interaction chdir=/vagrant/gymnastics-competition-system-api
