---
- name: Create sessions dev dir
  file: path=/dev/shm/jurymatch/var/sessions/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create cache dev dir
  file: path=/dev/shm/jurymatch/var/cache/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create logs dir
  file: path=/dev/shm/jurymatch/var/logs/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Copy the parameters distfile
  command: cp /vagrant/jurymatch/.env.dist /vagrant/jurymatch/.env creates=/vagrant/jurymatch/.env

- name: Composer install
  command: composer install --no-interaction --prefer-source --no-scripts --working-dir=/vagrant/jurymatch

- name: NPM install
  command: npm install chdir=/vagrant/jurymatch

- name: Bower packages install
  command: bower install chdir=/vagrant/jurymatch

- name: Build assets
  command: grunt dev chdir=/vagrant/jurymatch

- name: Install assets
  command: bin/console assets:install public --symlink chdir=/vagrant/jurymatch

#- name: Doctrine migrations
#  command: bin/console doctrine:migrations:migrate --no-interaction chdir=/vagrant/jurymatch
