---

nginx_server_templates_jurysysteem:
  - name: jurysysteem
    src: "{{ inventory_dir }}/roles/webserver/templates/http.conf.j2"
    ssl: off
    index: index.php
    web_root: "{{ project_root}}/jurysysteem/public"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://stackpath.bootstrapcdn.com https://cdn.jsdelivr.net  ; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; font-src 'self' data:"
    domains:
        - "jurysysteem.loc"
        - "www.jurysysteem.loc"
    rabbitmq_enabled: true

jurysysteem_db_user:     'jurysysteem'
jurysysteem_db_password: 'jurysysteem'

mariadb_databases_jurysysteem:
  - 'jurysysteem'

mariadb_users_jurysysteem:
  - {
    name:     "{{ jurysysteem_db_user }}",
    password: "{{ jurysysteem_db_password }}",
    priv:     "jurysysteem.*:ALL",
    host:     "%"
  }

# rabbitmq
rabbitmq_vhosts:
  - jurysysteem

rabbitmq_management_users:
  - username: "admin"
    password: "admin"
    role: administrator
    permissions:
      - vhost: jurysysteem
        configure_priv: .*
        read_priv: .*
        write_priv: .*
