nginx_server_templates_jurymatch:
  - name: jurymatch
    src: "{{ inventory_dir }}/roles/webserver/templates/http.conf.j2"
    ssl: off
    index: index.php
    web_root: "{{ project_root}}/jurymatch/public"
    domains:
      - "jurymatch.loc"
      - "www.jurymatch.loc"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com data:"

jurymatch_db_user:     'jurymatch'
jurymatch_db_password: 'jurymatch'

mariadb_databases_jurymatch:
  - 'jurymatch'

mariadb_users_jurymatch:
  - {
    name:     "{{ jurymatch_db_user }}",
    password: "{{ jurymatch_db_password }}",
    priv:     "jurymatch.*:ALL",
    host:     "%"
  }
