nginx_server_templates_speurtocht:
  - name: speurtocht
    src: "{{ inventory_dir }}/roles/webserver/templates/http.conf.j2"
    ssl: off
    index: index.php
    web_root: "{{ project_root}}/speurtocht/public"
    headers:
        Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
    domains:
        - "speurtocht.loc"
        - "www.speurtocht.loc"

speurtocht_db_user:     'speurtocht'
speurtocht_db_password: 'speurtocht'

mariadb_databases_speurtocht:
  - 'speurtocht'

mariadb_users_speurtocht:
  - {
    name:     "{{ speurtocht_db_user }}",
    password: "{{ speurtocht_db_password }}",
    priv:     "speurtocht.*:ALL",
    host:     "%"
  }
