nginx_server_templates_voedselbos:
  - name: voedselbos
    src: "{{ inventory_dir }}/roles/webserver/templates/http.conf.j2"
    ssl: off
    index: index.php
    web_root: "{{ project_root}}/voedselbos/public"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://stackpath.bootstrapcdn.com https://cdn.jsdelivr.net  ; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; font-src 'self' data:"
    domains:
        - "voedselbos.loc"
        - "www.voedselbos.loc"

voedselbos_db_user:     'voedselbos'
voedselbos_db_password: 'voedselbos'

mariadb_databases_voedselbos:
  - 'voedselbos'

mariadb_users_voedselbos:
  - {
    name:     "{{ voedselbos_db_user }}",
    password: "{{ voedselbos_db_password }}",
    priv:     "voedselbos.*:ALL",
    host:     "%"
  }
