---

nginx_server_templates_wie_is_de_beste:
  - name: wieisdebeste
    src: "{{ inventory_dir }}/roles/webserver/templates/http.conf.j2"
    ssl: off
    index: index.php
    web_root: "{{ project_root}}/wieisdebeste/public"
    headers:
      Content-Security-Policy: "default-src 'self' https://ka-f.fontawesome.com; script-src 'self' 'unsafe-inline' https://code.jquery.com https://stackpath.bootstrapcdn.com https://cdn.jsdelivr.net https://kit.fontawesome.com; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; font-src 'self' https://ka-f.fontawesome.com data:"
    domains:
        - "wieisdebeste.loc"
        - "www.wieisdebeste.loc"
    rabbitmq_enabled: true

wie_is_de_beste_db_user:     'wieisdebeste'
wie_is_de_beste_db_password: 'wieisdebeste'

mariadb_databases_wie_is_de_beste:
  - 'wieisdebeste'

mariadb_users_wie_is_de_beste:
  - {
    name:     "{{ wie_is_de_beste_db_user }}",
    password: "{{ wie_is_de_beste_db_password }}",
    priv:     "wieisdebeste.*:ALL",
    host:     "%"
  }
