---

- name: Create sessions dev dir
  file: path=/dev/shm/wieisdebeste/var/sessions/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create cache dev dir
  file: path=/dev/shm/wieisdebeste/var/cache/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create logs dev dir
  file: path=/dev/shm/wieisdebeste/var/logs/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Copy the env file
  command: cp /vagrant/wieisdebeste/.env.dist /vagrant/wieisdebeste/.env creates=/vagrant/wieisdebeste/.env

- name: Composer install
  command: composer install --no-interaction --prefer-source --no-scripts --working-dir=/vagrant/wieisdebeste

- name: Doctrine migrations
  command: bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration chdir=/vagrant/wieisdebeste
