---

- name: Add the nodesource.com trusted key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"

- name: Add the nodesource.com repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    update_cache: no

- name: Add the nodesource.com source repository
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    update_cache: yes

- name: Install Node.js & NPM
  apt:
    name: nodejs

- name: Check temp directory
  command: npm -g config get tmp
  register: npm_tmp_dir
  changed_when: False

- name: Set temp directory
  command: npm -g config set tmp /tmp
  when: npm_tmp_dir.stdout != '/tmp'

- name: Remove old temp directory
  file:
    path: "{{ npm_tmp_dir.stdout }}"
    state: absent
  when: npm_tmp_dir.stdout != '/tmp'
