nginx_server_templates_donargym:
  - name: donargym
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: index.php
    web_root: "{{ project_root}}/donargym.nl/current/public"
    domains:
      - "donargym.nl"
      - "www.donargym.nl"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://stackpath.bootstrapcdn.com https://cdn.jsdelivr.net  ; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; font-src 'self' data:"

donargym_db_user:     ~ # Placed in secure.yml
donargym_db_password: ~ # Placed in secure.yml

mariadb_databases_donargym:
  - 'donargym_production'

mariadb_users_donargym:
  - {
    name:     "{{ donargym_db_user }}",
    password: "{{ donargym_db_password }}",
    priv:     "{{ donargym_db_user }}.*:ALL",
    host:     "%"
  }
