nginx_server_templates_jurymatch_test:
  - name: jurymatch_test
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: index.php
    web_root: "{{ project_root}}/test.jurymatch.nl/current/public"
    domains:
      - "test.jurymatch.nl"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com data:"

jurymatch_test_db_user:     ~ # Placed in secure.yml
jurymatch_test_db_password: ~ # Placed in secure.yml

mariadb_databases_jurymatch_test:
  - 'jurymatchtest'

mariadb_users_jurymatch_test:
  - {
    name:     "{{ jurymatch_test_db_user }}",
    password: "{{ jurymatch_test_db_password }}",
    priv:     "{{ jurymatch_test_db_user }}.*:ALL",
    host:     "%"
  }
