---

deploy_user: deploy
project_root: /home/{{ deploy_user }}
bashrc_users:
  - "provision"

ssh_provision_user: "provision"

# NGINX
nginx_user:         www-data
nginx_group:        www-data
server_templates: "{{ nginx_server_templates_redirects + nginx_server_templates_donargym + nginx_server_templates_donarteamcup + nginx_server_templates_websites }}"

nginx_server_templates_redirects:
  - name: "markmeijerman.nl"
    src: "{{ inventory_dir }}/roles/webserver/templates/redirect.conf.j2"
    redirect_to: "https://www.linkedin.com/in/mjmeijerman/"
    domains:
      - "markmeijerman.nl"
      - "www.markmeijerman.nl"
  - name: "instachick.nl"
    src: "{{ inventory_dir }}/roles/webserver/templates/redirect.conf.j2"
    redirect_to: "https://www.instachicks.nl"
    domains:
      - "instachick.nl"
      - "www.instachick.nl"

nginx_http_params:
  client_max_body_size: "8M"
  ssl_protocols: TLSv1.3

# UFW
ufw_default_policy:
  - { direction: "incoming", policy: "deny" }

ufw_rules_to_create:
  - to_port: 22 # ssh
    rule: allow
  - to_port: 80 # Nginx
    rule: allow
  - to_port: 443 # Nginx
    rule: allow

# PHP

php8_ini_directives_global:
  disable_functions:      "exec, passthru, system, popen"
  allow_url_fopen:        1
  session.save_path:      "/var/lib/php{{ php8_version }}/sessions"
  session.cookie_secure:  1
  session.gc_probability: 1
  session.gc_divisor:     1000
  session.gc_maxlifetime: 3600
  always_populate_raw_post_data: "-1"

  opcache_fast_shutdown: 0
  opcache_interned_strings_buffer: 16
  opcache_max_accelerated_files: 10240
  opcache_memory_consumption: 128
  opcache_revalidate_freq: 0
  opcache_validate_timestamps: 0

  error_log: syslog

php8_ini_directives_fpm:
  upload_max_filesize: "8M"
  post_max_size: "8M"

php8_fpm_pool_enabled: yes
php8_fpm_pool_name: www
php8_fpm_pool_user: www-data
php8_fpm_pool_group: www-data
php8_fpm_pool_listen: "/run/php/php{{ php8_version }}-fpm.sock"
php8_fpm_pool_listen_mode: "0660"
php8_fpm_pool_pm: static
php8_fpm_pool_status_path: /status
php8_fpm_pool_pm_max_children: 128
php8_fpm_pool_pm_max_requests: 512
php8_fpm_pool_catch_workers_output: yes

# MYSQL
mariadb_bind_address:          "127.0.0.1"
mariadb_root_password:         ~ # Placed in secure.yml

mariadb_databases:
  - "{{ mariadb_databases_donargym }}"
  - "{{ mariadb_databases_donarteamcup }}"
  - "{{ mariadb_databases_websites }}"
mariadb_users: "{{ mariadb_users_donargym + mariadb_users_donarteamcup + mariadb_users_websites }}"
