nginx_server_templates_speurtocht:
  - name: speurtocht
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: index.php
    web_root: "{{ project_root}}/speurtocht.markmeijerman.nl/current/public"
    domains:
      - "speurtocht.markmeijerman.nl"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com data:"

speurtocht_db_user:     ~ # Placed in secure.yml
speurtocht_db_password: ~ # Placed in secure.yml

mariadb_databases_speurtocht:
  - 'speurtocht_production'

mariadb_users_speurtocht:
  - {
    name:     "{{ speurtocht_db_user }}",
    password: "{{ speurtocht_db_password }}",
    priv:     "{{ speurtocht_db_user }}.*:ALL",
    host:     "%"
  }
