nginx_server_templates_voedselbos:
  - name: voedselbos
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: index.php
    web_root: "{{ project_root}}/voedselbos.markmeijerman.nl/current/public"
    domains:
      - "voedselbos.markmeijerman.nl"
      - "tuin.markmeijerman.nl"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://stackpath.bootstrapcdn.com https://cdn.jsdelivr.net  ; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; font-src 'self' data:"

voedselbos_db_user:     ~ # Placed in secure.yml
voedselbos_db_password: ~ # Placed in secure.yml

mariadb_databases_voedselbos:
  - 'voedselbos_production'

mariadb_users_voedselbos:
  - {
    name:     "{{ voedselbos_db_user }}",
    password: "{{ voedselbos_db_password }}",
    priv:     "{{ voedselbos_db_user }}.*:ALL",
    host:     "%"
  }
