---
- name: Create sessions dev dir
  file: path=/dev/shm/voedselbos/var/sessions/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create cache dev dir
  file: path=/dev/shm/voedselbos/var/cache/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create logs dev dir
  file: path=/dev/shm/voedselbos/var/logs/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Copy the parameters distfile
  command: cp /vagrant/voedselbos/config/packages/parameters.yaml.dist /vagrant/voedselbos/config/packages/parameters.yaml creates=/vagrant/voedselbos/config/packages/parameters.yaml

- name: Copy the env file
  command: cp /vagrant/voedselbos/.env.dist /vagrant/voedselbos/.env creates=/vagrant/voedselbos/.env

- name: Composer install
  command: composer install --no-interaction --prefer-source --no-scripts --working-dir=/vagrant/voedselbos

- name: Doctrine migrations
  command: bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration chdir=/vagrant/voedselbos
